### ISSUE TITLE
French translation issue ?

### ISSUE THREAD

**Issue by trebmuh** [palinek/nm-tray#10]
Hi @palinek ,
I've been translating nm-tray into French this morning, but the [related commit](https://github.com/palinek/nm-tray/commit/98d03b52ff4e200882343a7c3e5cf899d55398af) isn't showing any translation (yet?). Did I do something wrong maybe or is it the usual workflow?

**Comment by palinek** [comment]
Hi.
First thanks for your contribution.
I'm not much familiar with the weblate... but as I understand it, the translatiosn made into the weblate service are pushed into the master repository (the nm-tray in this case) on regular basis (once a day?), but adding a language is pushed to remote instantly.

If pushed the changes manually now ...

**Comment by trebmuh** [comment]
You're welcome.
Thanks for your quick answer and explanation. And thanks for the manual push (which is a cherry on the cake).
