### ISSUE TITLE
New langauge on Weblate copies source to translation

### ISSUE THREAD

**Issue by scootergrisen** [palinek/nm-tray#20]
I created a new language on weblate but instead of starting a new blank translation Weblate seems to have copied all the source strings to the translated strings.

If i download the file the translated strings are empty.
But on Weblate the translated strings are not empty for some reason.

**Comment by palinek** [comment]
I do not host the weblate service nor do I control this behavior (I just use the free service which is provided by the weblate upstream).
If you believe, this is an error, please report it to the weblate upstream.
