### ISSUE TITLE
Context Menu (right click?)

### ISSUE THREAD

**Issue by GinoBombino** [palinek/nm-tray#24]
Hey,

I can't figure out why, but I have no right click context menu in your tray icon. I have that main 
Active Connections/Wifi/Known Connections. dialog but this comes up on both left and right clicks.

I have other QT5 based tray apps and they all work fine.
Your code appears to have a menu built `d->mTrayIcon.setContextMenu(&d->mContextMenu);`
but i can't get it to work.

BTW: I'm running, Gentoo w/AwesomeWM

any clues?

**Comment by palinek** [comment]
This is strange. What tray/panel are you using?

**Comment by GinoBombino** [comment]
It's the one built into awesomeWM,
I have a few other qt applications that don't have this issue.. so i'm not sure what the problem is..

**Comment by palinek** [comment]
> It's the one built into awesomeWM,

Does it provide the status notifier interface or the legacy xembed?

**Comment by GinoBombino** [comment]
I'm pretty sure it's legacy xembed

**Comment by GinoBombino** [comment]
I also run https://github.com/sieren/QSyncthingTray without any issues

**Comment by GinoBombino** [comment]
Ok I fixed this by altering your onActivated function and add a switch case, (basically similar to the QT docs)
-    void onActivated();
+    void onActivated(QSystemTrayIcon::ActivationReason reason);
 
I'll make a pull request for you..
I am not by any means a C++ programmer btw.. so let me know if this isn't OK..

Thanks.

**Comment by palinek** [comment]
Oh... now I replicated the issue here with the legacy xembed tray. The problem here is, that in case of context menu triggering both menus are shown (and probably one covers the other).

**Comment by palinek** [comment]
Fixed by e901b63e205e6ce1b9de3d963d46df7974b2ee3a
