### ISSUE TITLE
Use x-terminal-emulator instead of xterm

### ISSUE THREAD

**Issue by tsimonq2** [palinek/nm-tray#30]
Not all distributions (like Lubuntu) want to ship xterm by default. It should refer to `x-terminal-emulator` instead, so the default terminal can be used.

https://phab.lubuntu.me/D3

**Comment by palinek** [comment]
> https://phab.lubuntu.me/D3

This link wants registration.... so I can't get there.

**Comment by tsimonq2** [comment]
> This link wants registration.... so I can't get there.

Waaat... fixing.

**Comment by palinek** [comment]
> Isn't x-terminal-emulator a Debian (and derivates) thing? What about xdg-terminal ?

How many of such "universal" aliases exist? :)

@tsimonq2 
Why don't  you just override the upstream default with your own system-wide config file?

**Comment by jubalh** [comment]
> How many of such "universal" aliases exist? :)

:D
I think `xdg-open` is the cross distribution way by Freedesktop.
x-terminal-emulator was probably older and introduced by Debian AFAIK.

**Comment by agaida** [comment]
@jubalh - you are nearly right. There are some debian specific things like provides and alternatives that you don't find anywhere else. The idea behind is that more than one package could provide the whished functionality. In case of terminal emulators:
```
Package: xterm
Version: 333-1
Priority: optional
Section: x11
Maintainer: Debian X Strike Force <debian-x@lists.debian.org>
Installed-Size: 2.138 kB
Provides: x-terminal-emulator

Package: konsole
Version: 4:18.04.0-1
Priority: optional
Section: kde
Maintainer: Debian/Kubuntu Qt/KDE Maintainers <debian-qt-kde@lists.debian.org>
Installed-Size: 3.764 kB
Provides: x-terminal-emulator

Package: mate-terminal
Version: 1.20.1-1
Priority: optional
Section: x11
Maintainer: Debian+Ubuntu MATE Packaging Team <debian-mate@lists.debian.org>
Installed-Size: 391 kB
Provides: x-terminal-emulator

Package: gnome-terminal
Version: 3.28.2-1
Priority: optional
Section: gnome
Maintainer: Debian GNOME Maintainers <pkg-gnome-maintainers@lists.alioth.debian.org>
Installed-Size: 1.150 kB
Provides: x-terminal-emulator
```
All these packages provide the virtual package x-terminal-emulator, any of the packages can fulfill this dependency.

But this is not the x-terminal-editor @tsimonq2 is talking about. The second debian and derivatives thing are alternatives. Alternatives are really fun: As for virtual packages we have some virtual binaries - one create a alternative in /etc/alternatives and link this alternative into /usr/bin. /etc/alternatives/$foo links to the real binary - nice concept, if one know how to handle. 

In case of x-terminal-editor it looks like:
![](https://i.imgur.com/12CHZoT.png)
```
% which x-terminal-emulator                                                                                                   
/usr/bin/x-terminal-emulator
% ls -l /usr/bin/x-terminal-emulator
lrwxrwxrwx 1 root root 37 Okt 12  2016 /usr/bin/x-terminal-emulator -> /etc/alternatives/x-terminal-emulator
% ls -l /etc/alternatives/x-terminal-emulator                                                                                 
lrwxrwxrwx 1 root root 14 Feb  6  2018 /etc/alternatives/x-terminal-emulator -> /usr/bin/xterm
```
easy, isn't it? :dark_sunglasses:

**Comment by agaida** [comment]
Added Dependency qterminal | x-terminal-emulator - i guess we can close this one.
