### ISSUE TITLE
Taskbar or menu icons hard to see when both have different background

### ISSUE THREAD

**Issue by hmollercl** [palinek/nm-tray#39]
Since icons.cpp use symbolic icons for taskbar and menu, when taskbar has a dark background and menu light, icons are hard to see in task bar but does look good in menu.

network-manager from gnome use non symbolic for both, and they end up showing good in task bar but bad in menu, however, when mouse-over the connection they look good (it add a dark background on mouse-over)

In the menu is problematic for wireless signal since the icon show signal strength.

My suggestion would be to use symbolic icons for menu, but non-symbolic for taskbar.

**Comment by palinek** [comment]
I can see nothing that can be done here on nm-tray's side. Other user (use case) can require just the opposite of your suggestion.

You can
- use icon theme w/o *-symbolic icons
- use configuration options (if any) of your panel

**Comment by hmollercl** [comment]
To clarify, hHere are some screenshots. In the first one you see both taskbar icons, the dark one is nm-tray which also has its connection menu open. As you can see nm-tray taskbar icon is hard to see but connections icons are ok. On the other hand network-manager-gnome (non symbolic) taskbar icon looks white.
![nm-tray1](https://user-images.githubusercontent.com/30954443/58926382-09cef100-8719-11e9-81e0-cbba747de452.png)
In the second one, you can also see both taskbar icons, but in this case the menu icons are hard to see (non-symbolic) of netwoork-manager-gnome.
![nm-tray2](https://user-images.githubusercontent.com/30954443/58926395-15221c80-8719-11e9-8fdd-65bc5775694f.png)
In the third screenshot you can see how lxqt-powermanagement handles the issues in a good manner, taskbar icon light on dark taskbar but menu icons dark on light background. In case of the menu it uses xdg:icon https://github.com/lxqt/lxqt-powermanagement/blob/master/src/trayicon.cpp#L61 and it doesn't use symbolic for taskbar icon (even when it use the theme icon) https://github.com/lxqt/lxqt-powermanagement/blob/master/src/iconproducer.cpp
![nm-tray3](https://user-images.githubusercontent.com/30954443/58926503-8c57b080-8719-11e9-98e2-23a963c44435.png)

My understanding is that symbolic icons are for instances where you don't want/need fancy icons (https://wiki.gnome.org/Design/OS/SymbolicIcons), I agree with that in the menu, but not necessary in today's taskbars/panel.
That's why I would suggest using symbolic for menus but not for taskbar, but there might be other approaches.
I agree that changing the icon theme to a more colorfull ones would change the issue, and also having menu and taskbar with same bakcground color, but there are other programs that have solveed this, like lxqt-powermanagement.

**Comment by palinek** [comment]
Please, check if https://github.com/palinek/nm-tray/commits/icon_symbolic implements your suggestion.

**Comment by hmollercl** [comment]
wow, that was quick! Thanks! At least with wired connection worked like a charm, tonight I will test it with wireless and let you know.

**Comment by hmollercl** [comment]
perfect, that solve the issue, non-symbolic tray icon, simbolic for the list
thanks!
![nm-tray-solved](https://user-images.githubusercontent.com/30954443/58999657-c9cd4400-87d4-11e9-9e55-1578ef868501.png)

**Comment by palinek** [comment]
Merged into master -> ecbe243
