### ISSUE TITLE
No visual feedback to "connecting" state

### ISSUE THREAD

**Issue by c-cesar** [palinek/nm-tray#4]
Hi. 
First, thanks for your work.
Wireless connections can be in "connecting" state for quite a long time, and wile getting the authentication nm-tray shows me the same icon of connected networks.

**Comment by palinek** [comment]
Don't you see the "connecting" icon while establishing the wi-fi connection? (the _symbolic_ name of icon when connection acquiring is `network-wireless-acquiring-symbolic` or `network-wireless-acquiring`)

Does the icon theme, you are currently using, provide such icons?

Note: I've pushed the fix for showing/updating the information on app startup recently in @4e249b0

**Comment by c-cesar** [comment]
making some tests here. Works with Faenza e Adawita icon themes, but not with Breeze or Oxygen. Looking this icon packs contents, this is a but in the icon themes that not provides this acquiring status. 
Thanks.

**Comment by DarkknightAK** [comment]
Breeze and Oxygen maintainer, can you post a screenshot.
Thanks

**Comment by c-cesar** [comment]
![screenshot_20170107_182441](https://cloud.githubusercontent.com/assets/350914/21744918/dcee502a-d506-11e6-8ab9-dd2636d9e72b.png)
![screenshot_20170107_182505](https://cloud.githubusercontent.com/assets/350914/21744917/dcea1a00-d506-11e6-8fb2-4e66a654ab69.png)
![screenshot_20170107_182334](https://cloud.githubusercontent.com/assets/350914/21744919/dcf0e24a-d506-11e6-86c6-2979267d2c1e.png)

**Comment by palinek** [comment]
> Breeze and Oxygen maintainer, can you post a screenshot.

@DarkknightAK
[here](https://github.com/palinek/nm-tray/blob/master/src/icons.cpp#L33) are the icon names, that are used (now I know, that there is no need to test _foo-symbolic_ and _foo_ as the standard says that _foo_ should be considered also if _foo-symbolic_ is not present..)

Are there any others suitable icons, that can be used for the `aquiring` state in Breeze/Oxygen?
