### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by hmollercl** [palinek/nm-tray#41]
Hi,
   do you plan to have a new release soon? With the non-symbolic tray icon? Just wanted to know so we don't have to apply the patch in lubuntu and could only use the release.
Thanks!

**Comment by palinek** [comment]
I don't have any release schedule. But it's not a big deal to make a new release for me.
Currently there are only minor fixes and translations changes after the last release.

I can make the release If you wish.

Should I?

**Comment by agaida** [comment]
https://wiki.ubuntu.com/EoanErmine/ReleaseSchedule

only a thought - it's still time brother ... @hmollercl  - the perfect way would be if there is an upstream release, the package will be packaged in debian and can be directly imported into Ubuntu. So - Debian has released three days ago, sid is open - @palinek: End of July would be great, it will take me one day to upload directly to sid. If you and @tsimonq2 agree we should schedule this to beginning of August, maybe with the open PR's merged.

**Comment by hmollercl** [comment]
That would be great.

**Comment by wxl** [comment]
You're talking my language, @agaida. Ubuntu's next release is October and. FeatureFreeze is end of August, so if we have everything coming down beginning of August should be no problem at all. I don't think FeatureFreeze would even really stop us given the relatively minor fixes.

**Comment by palinek** [comment]
OK, guys. Ping me then and I'll make the release ASAP.

**Comment by tsimonq2** [comment]
ack on scheduling this at the beginning of August.

**Comment by tsimonq2** [comment]
@palinek ping

**Comment by palinek** [comment]
Done -> https://github.com/palinek/nm-tray/releases/tag/0.4.3

**Comment by jubalh** [comment]
Ok! Update is on it's way to openSUSE.
