### ISSUE TITLE
Foreground color offers no contrast

### ISSUE THREAD

**Issue by vinnarkillen** [palinek/nm-tray#42]
I installed lubuntu and nm-tray icon displaying wifi strength has a gray foreground color similar to the background color. Difficult to see wifi level, or the nm-tray icon even (lower right corner on the screen, next to the clock).

##### Expected Behavior

Change to a constrasting foreground color, for example the blue used elsewhere in lubuntu.

##### Steps to Reproduce (for bugs)

1.
2.
3.
4.

##### System Information

* Distribution & Version:
* Kernel Version:
* Qt Version:
* Network-Manager Version:
* nm-tray Version:
* Package version:

**Comment by palinek** [comment]
nm-tray doesn't provide any icons. It uses icons from your chosen icon set.

**Comment by hmollercl** [comment]
This is solved here https://github.com/palinek/nm-tray/commit/ecbe243339cc4a89dbaf3c37362cd0d963e0a22d, we are waiting for a new release https://github.com/palinek/nm-tray/issues/41 to put it in lubuntu.
