### ISSUE TITLE
Unable to connect to openVPN

### ISSUE THREAD

**Issue by pcmagno** [palinek/nm-tray#47]
##### Expected Behavior
When trying to connect to the added openVPN connection, it immediately fails.

Here's the notification message that pops up:
```
NetworkManager(nm-tray)
Connection lost
No longer connected to vpn 'my-vpn-conf'
```

Here's the error message on the terminal:
```
nm-tray: void NmModelPrivate::onActiveConnectionAdded(const QString&) /org/freedesktop/NetworkManager/ActiveConnection/29  is currently invalid...
nm-tray: void NmModelPrivate::onActiveConnectionRemoved(const QString&) /org/freedesktop/NetworkManager/ActiveConnection/29  is currently invalid...
```

I'm only unable to connect when using nm-tray. When I use nmcli or nm-applet, I can connect just fine. I also noticed that when I connect through nm-applet, there's an input dialog that asks for keyring password. Whereas with nm-tray, it just immediately fails.

##### Steps to Reproduce (for bugs)
1. It always fails.

##### System Information
* Distribution & Version: Fedora 31
* Kernel Version: 5.4.12-200.fc31.x86_64
* Qt Version: 5.13
* Network-Manager Version: 1.20.10-1.fc31
* nm-tray Version: 0.4.2
* Package version:

**Comment by hmollercl** [comment]
I think this could be related with https://github.com/palinek/nm-tray/issues/44 
At this time nm-tray doesn't have an "ask for password" feature. Workaround is to save the password (I believe you need to save for all users) or connect via cli.

**Comment by adolfombarros** [comment]
I'm using Password with Certificates (TLS) authentication...
@hmollercl suggested a workaround is to save the password for all users.
In my case, I need to save the key password for all users too!
