### ISSUE TITLE
No icon in system tray lxqt desktop

### ISSUE THREAD

**Issue by sandangel** [palinek/nm-tray#5]
I have installed nm-tray-git package but there is no icon in system tray. Does it work with lxqt ?

**Comment by palinek** [comment]
Please, be more specific about the "no icon".

**Comment by sandangel** [comment]
I installed nm-tray-git in aur with command yaourt nm-tray-git, I also install and enable NetworkManager.service. It show the icon in system tray of plasma desktop, but when I switch to lxqt desktop, there is no icon in system tray. I thought nm-tray-git package work like network-manager-applet right?

**Comment by palinek** [comment]
> It show the icon in system tray of plasma desktop, but when I switch to lxqt desktop, there is no icon in system tray. 

What icon theme are you using?
How did you install LXQt?
Which of "Status Notifier Plugin", "System tray" plugins are you using?
Is there an "empty space" where the icon should reside (the context menu can be shown)? Or  is there no area belonging to `nm-tray` at all?

Here, with the "Numix Circle Light" theme, I'm seeing it correctly:
- on wired connection ![screenshot](https://cloud.githubusercontent.com/assets/10990929/22905810/04e6c6fe-f242-11e6-8e57-2ac64dd0b56f.png)
- no network connection ![screenshot](https://cloud.githubusercontent.com/assets/10990929/22905873/4153284e-f242-11e6-9fee-1d127ebbf12d.png)
- on wi-fi ![screenshot](https://cloud.githubusercontent.com/assets/10990929/22905949/94ae5f90-f242-11e6-8875-4a69821757a3.png)
- while connecting to wi-fi ![screenshot](https://cloud.githubusercontent.com/assets/10990929/22905906/6904787a-f242-11e6-848b-c009aec9747e.png)

**Comment by sandangel** [comment]
1. I'm using Numix Circle Light theme.
2. I have install lxqt-git group in my arch linux virtualbox-guest on my PC with linux mint host. And on my laptop, I have installed arch linux on disk, with lxqt desktop installed by installing lxqt group (not lxqt-git). Problem with both of them.
3.  I 'm using the default System tray and Status Notifier Plugin of Lxqt panel.
4. I put System tray and Status Notifier Plugin next to each other, and between Date & time and removable media widget, but there is no empty space. I have a attached an image below.
5. here is the output of command "yaourt nm-tray-git"        
    1 aur/nm-tray-git r37.abbe586-1 [installed: r42.4e249b0-1] (3) (0.71)
        Pure Qt NetworkManager front-end residing in panels
    ==> Enter n° of packages to be installed (ex: 1 2 3 or 1-3)
    ==> -------------------------------------------------------
    ==> 
6. I have enable NetworkManager.service by systemctl enable NetworkManager
    systemctl status NetworkManager
    ● NetworkManager.service - Network Manager
       Loaded: loaded (/usr/lib/systemd/system/NetworkManager.service; enabled; vendor preset: 
       Active: active (running) since Tue 2017-02-14 08:29:00 JST; 58min ago
         Docs: man:NetworkManager(8)
     Main PID: 258 (NetworkManager)
        Tasks: 3 (limit: 4915)
       CGroup: /system.slice/NetworkManager.service
               └─258 /usr/bin/NetworkManager --no-daemon
![screenshot_2017-02-14_09-23-25](https://cloud.githubusercontent.com/assets/22189661/22909396/47ac0846-f297-11e6-9209-c24ee3d5326e.png)

**Comment by palinek** [comment]
Is the the `nm-tray` even running? Did you run it?
(we do not provide any "autostart" .desktop file, so you need to start nm-tray manualy)

**Comment by palinek** [comment]
@sandangel I've added the "autostart" .desktop entry in @9c480cc. If you update your package now, the `nm-tray` should be started automatically in LXQt session.

**Comment by sandangel** [comment]
I got it worked. But it is not automatic update by yaourt -Syu --aur, I had to reinstall nm-tray-git. Anyway, It works. Thank you very much.
