### ISSUE TITLE
Unclear how to disconnect from SSID

### ISSUE THREAD

**Issue by jidak** [palinek/nm-tray#51]
When connected to a wireless network, there is no option in the menu to disconnect. Clicking again on the connected SSID disconnects the network, but the resultant notification message says the network has been 'lost', implying that there was a problem or error.

Is clicking on the connected SSID meant to be the correct method to disconnect?

It would be useful to have a separate menu entry labelled 'Disconnect' so that the functionality is obvious. Also, the notification message should say the network has been disconnected, rather than lost.

**Comment by palinek** [comment]
> Is clicking on the connected SSID meant to be the correct method to disconnect?

Yes, that's the intended way to disconnect.
