### ISSUE TITLE
Multiple instances of nm-tray on xfce4 Debian bullseye

### ISSUE THREAD

**Issue by Jim-Foo** [palinek/nm-tray#53]
I was having problems opening windows getting error that limit was reached. Searched and found the following command to list X11 clients:

lsof +c0 /usr/lib/x86_64-linux-gnu/libX11.so.6|cut -d' ' -f1

result was:

pulseaudio
xfce4-session
at-spi-bus-laun
at-spi2-registr
xfwm4
xfsettingsd
xfce4-panel
xfdesktop
panel-7-battery
panel-1-pulseau
panel-16-xfce4-
xfce4-notifyd
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
nm-tray
xfce4-power-man
nm-tray
nm-tray
nm-tray
nm-tray
Thunar
nm-tray
applet.py
ayatana-indicat
parcellite
blueman-applet
xiccd
polkit-gnome-au
nm-applet
blueman-tray
xfce4-terminal
firefox-esr

I had switched off notifications from nm-tray because it was spamming the screen with many notifications. The solution was to uninstall. I didn't seem to have the same problem when using lxde so it might be an xfce bug.

nm-tray        0.4.3-2+b1
network-manager     1.30.0-2
Linux 5.10.0-6-amd64 #1 SMP Debian 5.10.28-1 (2021-04-09) x86_64 GNU/Linux

##### Steps to Reproduce (for bugs)

1.
2.
3.
4.

##### System Information

* Distribution & Version:
* Kernel Version:
* Qt Version:
* Network-Manager Version:
* nm-tray Version:
* Package version:

**Comment by palinek** [comment]
You need to figure you, why are there so many instances of nm-tray running. nm-tray on it's own doesn't anyhow try re-spawn it's process.

**Comment by slidinghotdog** [comment]
Xfce saves and restores sessions (running programs), so if u have nm-tray running when it's saved (depends on xfce settings), next login it will open automatically, and if u added it to autostart it will open again, adding one instance every login... I think u can disable this feature somewhere in xfce settings, or the easier way is to close all instances, remove from autostart and just open 1 time.. It will be saved and autostarted again by the session thing...


Another way would be for nm-tray to only allow one instance of itself.
