### ISSUE TITLE
QT error on startup and in ~/.xsession-errors

### ISSUE THREAD

**Issue by EnDe** [palinek/nm-tray#55]
##### Expected Behavior
* show a human readable/understandable message, if an error ocours, best with hints
* avoid writing same error message multiple time

##### Current Behavior
1. nm-tray prints following error on startup:
<code>QSystemTrayIcon::setVisible: No Icon set</code>
2. nm-tray prints more than 10 per second in  ~/.xsession-errors
<code>(wrapper-2.0:2799): libsystray-CRITICAL **: 10:06:03.563: sn_item_invalidate: assertion 'XFCE_IS_SN_ITEM (item)' failed</code>
which reults in roughly 100MB per day.

##### Possible Solution
* Errors returned from QT-system should be catched and reported with context of nm-tray.
* nm-tray should have an option which reports expected resources (like icons) and dependencies.
* use build-in defaults if something is missing (yes, I know, this is a load of work).

##### Steps to Reproduce (for bugs)

Debugging is hard, as it depends on the used and configured QT.
The <code>QSystemTrayIcon...</code> message can be reproduced as follows (assuming your theme is set to Adwaita,  otherwise replace by proper name):
1. mv /usr/share/icons/Adwaita{,-DISABLED}
2. nm-tray
3.  mv /usr/share/icons/Adwaita{-DISABLED,}

The error in  ~/.xsession-errors is hard to reproduce (no guarantee):
1. mv /usr/share/icons/Adwaita{,-DISABLED}
1. kill Xorg # or whatever X-Server is used
1. start Xorg # and login
1. nm-tray
1. mv /usr/share/icons/Adwaita{-DISABLED,}
1.  kill Xorg
1. start Xorg

##### Context
Probably installing any or all of following packages (debian names) avoids the problem:
* adwaita-icon-theme
* paper-icon-theme

The continuous writing of the <code>libsystray-CRITICAL</code> probaly happens in
<code>TrayPrivate::refreshIcon()</code> in tray.cpp

##### System Information

* Distribution & Version: Devuan 4
* Kernel Version: 5.10.0-9-amd64
* Qt Version: 5
* Network-Manager Version: 1.30.0
* nm-tray Version: 0.4.2
* Package version:

**Comment by palinek** [comment]
@EnDe can you, please, test the #56 with your "failing" environment?

**Comment by EnDe** [comment]
tested: both descibed errors are still there

**Comment by EnDe** [comment]
IMHO the errors in ~/.xsession-errors basicly seem to be a QT problem, as they also occour when using other tray for NetworkManager like cmst
however, the message is definitely triggerd by nm-tray (or cmst) in short periods (every 1 to 5 seocnd)

**Comment by palinek** [comment]
> using other tray for NetworkManager like cmst

cmst is ConnMan frontend, not NetworkManager one

**Comment by EnDe** [comment]
correct, but the errors in ~/.xsession-errors are still triggerd by nm-tray

**Comment by palinek** [comment]
#56 merged
