### ISSUE TITLE
No icon

### ISSUE THREAD

**Issue by Scorpion2185** [palinek/nm-tray#58]
`nm-tray` doesn't have any icon it is an empty space in the tray.
The package doesn't install any, I am using the Debian package:
```
dpkg -L nm-tray
/.
/etc
/etc/xdg
/etc/xdg/autostart
/etc/xdg/autostart/nm-tray-autostart.desktop
/usr
/usr/bin
/usr/bin/nm-tray
/usr/share
/usr/share/applications
/usr/share/applications/nm-tray.desktop
/usr/share/doc
/usr/share/doc/nm-tray
/usr/share/doc/nm-tray/README.md
/usr/share/doc/nm-tray/changelog.Debian.amd64.gz
/usr/share/doc/nm-tray/changelog.Debian.gz
/usr/share/doc/nm-tray/copyright
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/nm-tray
```
It shows this error when launching it:
```
nm-tray
QSystemTrayIcon::setVisible: No Icon set
```
##### Expected Behavior
Icons show in the tray.

##### Current Behavior
No icon.
##### Possible Solution
Fixing missing icons in the dependency?

##### Steps to Reproduce (for bugs)
Debian with only openbox installed , no task selected.

##### System Information

* Distribution & Version: Debian GNU/Linux 11 (bullseye) x86_64
* Kernel Version: 5.10.0-13-amd64 
* Qt Version: is this `qmake-qt5`? It isn't installed.
* Network-Manager Version: 1.30.0-2
* nm-tray Version: 0.4.3-2+b1
* Package version: 0.4.3-2+b1

**Comment by palinek** [comment]
I forgot about #56. I thought it is already merged. Merged it now.

dup of #55

**Comment by Scorpion2185** [comment]
@palinek What package can provide the "default" icons?

**Comment by Scorpion2185** [comment]
also can you release a new version? For packaging.

**Comment by palinek** [comment]
> What package can provide the "default" icons?

You can choose whatever icon set package you like.

**Comment by Scorpion2185** [comment]
I have Adwaita as icon theme, and the only other one available is Gnome.
Do I need some other package?

**Comment by Scorpion2185** [comment]
I have Adwaita as icon theme, and the only other one available is Gnome. No icon at all.
Do I need some other icon package?

While on another machine, with also Breeze and others, only initially if there is no connection no icon.
Afterward I have icons even if the connection is lost.

**Comment by palinek** [comment]
- this is what I see for no active connection:
-- with breeze
![screenshot](https://user-images.githubusercontent.com/10990929/161600671-14c91f8e-5464-4a5f-95b0-6aa7e0481657.png)
-- with Adwaita
![screenshot](https://user-images.githubusercontent.com/10990929/161601038-21afdede-967a-4734-b5a3-6bd7d87c814e.png)

**Comment by Scorpion2185** [comment]
How can I see what path `nm-tray` is looking for Adwaita icons?

**Comment by Scorpion2185** [comment]
How can I see what icons `nm-tray` is looking for and in what path?

**Comment by palinek** [comment]
You can read the icon theme specification - https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html

All icon names ever used by nm-tray can be seen here https://github.com/palinek/nm-tray/blob/master/src/icons.cpp#L55

**Comment by Scorpion2185** [comment]
I have that icon, it is `network-offline` from `Adwaita/legacy` right?

`lxpanel` applet has these:
![2022-04-05_21-45-05](https://user-images.githubusercontent.com/32654091/162053378-cf3d4c90-33d3-45a4-88de-c9db1e66b599.png)
![2022-04-05_21-45-16](https://user-images.githubusercontent.com/32654091/162053382-8936dc63-8c1b-438f-a5d4-27264d78053f.png)

`nm-tray` no icon at all. 
I tried update the Debian package but error.

**Comment by Scorpion2185** [comment]
I have that icon, it is `network-offline` from `Adwaita/legacy` right?

`lxpanel` applet has these:
![2022-04-05_21-45-05](https://user-images.githubusercontent.com/32654091/162053378-cf3d4c90-33d3-45a4-88de-c9db1e66b599.png)
![2022-04-05_21-45-16](https://user-images.githubusercontent.com/32654091/162053382-8936dc63-8c1b-438f-a5d4-27264d78053f.png)

`nm-tray` no icon at all. 
I tried to update the Debian package but error.

**Comment by Scorpion2185** [comment]
I have that icon, it is `network-offline` from `Adwaita/legacy` right?

`lxpanel` applet has these:
![2022-04-05_21-45-05](https://user-images.githubusercontent.com/32654091/162053378-cf3d4c90-33d3-45a4-88de-c9db1e66b599.png)
![2022-04-05_21-45-16](https://user-images.githubusercontent.com/32654091/162053382-8936dc63-8c1b-438f-a5d4-27264d78053f.png)

`nm-tray` no icon at all.
