### ISSUE TITLE
Unintuitive disconnect on right click on connections list

### ISSUE THREAD

**Issue by rysson** [palinek/nm-tray#59]
Unintuitive clicks on connections list. Right click usually opens menu (if available). Now it just call action – disconnect for example.

##### Expected Behavior
Allow only left click (ignore right and middle).

##### Current Behavior
Any mouse button execute an action (connect and disconnect).

##### Steps to Reproduce (for bugs)
1. Open connection link
2. Right click on connection

##### Context
Accident disconnections.

##### System Information

* Distribution & Version: Debian testing
* Kernel Version: 5.16.0-5-amd64
* Qt Version: 5.15.2
* Network-Manager Version: 1.36.4
* nm-tray Version: 41185e6
* Package version: —

**Comment by palinek** [comment]
Can you, please, check with #60 ?

**Comment by rysson** [comment]
PR #60 resolves this request, thank you very mach.
