### ISSUE TITLE
Autostart desktop file: a "OnlyShowIn" key must be included

### ISSUE THREAD

**Issue by rapgro** [palinek/nm-tray#8]
+ desktop-file-validate /home/builder/rpmbuild/BUILDROOT/nm-tray-0.3.0-1.fc27.x86_64/usr/share/applications/nm-tray.desktop
/home/builder/rpmbuild/BUILDROOT/nm-tray-0.3.0-1.fc27.x86_64/usr/share/applications/nm-tray.desktop: hint: value "Network;System;Monitor;Qt;TrayIcon" for key "Categories" in group "Desktop Entry" contains more than one main category; application might appear more than once in the application menu
/home/builder/rpmbuild/BUILDROOT/nm-tray-0.3.0-1.fc27.x86_64/usr/share/applications/nm-tray.desktop: error: value item "TrayIcon" in key "Categories" in group "Desktop Entry" is a reserved category, so a "OnlyShowIn" key must be included

**Comment by palinek** [comment]
Removed the `TrayIcon` in bb62435.
(together with 95800b7 it keeps `desktop-file-validate` quiet)
